name: Android each commit workflow

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint
        run: bash ./gradlew ktlintCheck

      - name: Upload source lint results 1
        uses: actions/upload-artifact@v4
        with:
          name: lintResults
          path: '**/build/reports/ktlint/ktlint*SourceSetCheck/ktlint*SourceSetCheck.txt'
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: bash ./gradlew testReleaseUnitTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/test-results/testReleaseUnitTest/TEST-*.xml'
